# Generated by Django 4.2 on 2023-04-11 05:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='duration',
            new_name='audio_duration',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='release_date',
        ),
        migrations.AddField(
            model_name='episode',
            name='audio_fize',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='episode',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='episode',
            name='slug',
            field=models.SlugField(default='new-slug', max_length=250, unique_for_date='publish'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=9),
        ),
        migrations.AddField(
            model_name='episode',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcast',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='podcast',
            name='slug',
            field=models.SlugField(default='new-podcast', max_length=250, unique='publish'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcast',
            name='status',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='public', max_length=7),
        ),
        migrations.AddField(
            model_name='podcast',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
