# Generated by Django 4.2.1 on 2023-05-11 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_alter_podcast_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='category',
            new_name='categories',
        ),
    ]
