# Generated by Django 4.2 on 2023-04-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_rename_duration_episode_audio_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='audio_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
