# Generated by Django 4.2.1 on 2023-05-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_rename_category_podcast_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique_for_date='publish'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
