# Generated by Django 4.2.1 on 2023-05-17 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('podcasts', '0004_alter_episode_slug_alter_podcast_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
