# Generated by Django 4.2 on 2023-04-11 05:48

from django.db import migrations, models
import podcasts.utils


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_rename_audio_fize_episode_audio_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to=podcasts.utils.get_image_upload_path),
        ),
    ]
