# Generated by Django 4.2 on 2023-04-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0006_episode_creater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='creater',
            new_name='creator',
        ),
    ]
