# Generated by Django 4.2 on 2023-04-24 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('podcasts', '0008_remove_episode_creator_podcast_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcasts_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
