# Generated by Django 4.2 on 2023-04-27 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_alter_user_following'),
        ('podcasts', '0010_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Following',
        ),
    ]
